"""
Converts drugs_parsed.json + drugs_chunks.json into Flyway migration SQL files.

Usage:
    python3 generate_sql.py

Inputs:
    drugs_parsed.json   — output of parse_drugs.py (Claude's structured output)
    drugs_chunks.json   — output of chunk_drugs.py (category metadata)

Outputs:
    ../src/main/resources/db/migration/V3__seed_categories.sql
    ../src/main/resources/db/migration/V4__seed_drugs.sql
    ../src/main/resources/db/migration/V5__seed_associations.sql
"""

import json
import pathlib
import re
from collections import defaultdict

MIGRATIONS_DIR = pathlib.Path("../src/main/resources/db/migration")

# ── helpers ──────────────────────────────────────────────────────────────────

HAS_CHINESE = re.compile(r"[一-鿿㐀-䶿]")


def clean_category(raw: str) -> str:
    """Keep only the French part: strip trailing pinyin and Chinese characters."""
    # Remove parentheticals containing Chinese or multi-word pinyin: "(run xia yao 潤下藥)"
    s = re.sub(r"\s*\([^)]*(?:[一-鿿㐀-䶿]|[a-z]{2,}\s+[a-z])[^)]*\)\s*$", "", raw)
    # Remove trailing "Pinyin 漢字" standalone suffix: "Huo xue zhi tong yao 活血止痛藥"
    s = re.sub(r"\s+[A-Z][a-z]+(?:\s+[a-z]+)+(?:\s+[一-鿿㐀-䶿]+)+\s*$", "", s)
    return s.strip()


def q(value: str | None, max_len: int = 255) -> str:
    """Escape a string for SQL single-quoted literals, or NULL."""
    if value is None:
        return "NULL"
    truncated = str(value)[:max_len]
    escaped = truncated.replace("'", "''")
    return f"'{escaped}'"


def normalize(name: str) -> str:
    """Lowercase + collapse spaces for fuzzy pinyin matching."""
    return re.sub(r"\s+", " ", name.strip().lower())


# ── load data ────────────────────────────────────────────────────────────────

with open("drugs_parsed.json", encoding="utf-8") as f:
    _raw = json.load(f)

# Flatten: the batch API occasionally returns a list-of-objects instead of one object
parsed: list[dict] = []
for item in _raw:
    if isinstance(item, dict):
        parsed.append(item)
    elif isinstance(item, list):
        parsed.extend(x for x in item if isinstance(x, dict))

with open("drugs_chunks.json", encoding="utf-8") as f:
    chunks: list[dict] = json.load(f)

# Build category lookup: normalized pinyin → category name
category_by_pinyin: dict[str, str] = {
    normalize(c["pinyin"]): c["category"] for c in chunks
}

# Associate each parsed drug with its category
for drug in parsed:
    key = normalize(drug.get("chineseName", ""))
    raw_cat = category_by_pinyin.get(key, "Unknown")
    drug["_category"] = clean_category(raw_cat)

# Collect all known pinyin names (for filtering associations)
known_pinyin: set[str] = {normalize(d.get("chineseName", "")) for d in parsed}

# ── V3 — categories ──────────────────────────────────────────────────────────

# Unique categories in insertion order
seen_categories: dict[str, None] = {}
for drug in parsed:
    seen_categories[drug["_category"]] = None
unique_categories = list(seen_categories.keys())

v3_lines = [
    "-- Seed drug categories",
    "-- Generated by generate_sql.py",
    "",
]
for cat in unique_categories:
    v3_lines.append(f"INSERT INTO drug_category (name) VALUES ({q(cat)});")

# ── V4 — drugs ───────────────────────────────────────────────────────────────

v4_lines = [
    "-- Seed drugs (properties, effects, contraindications, etc.)",
    "-- Generated by generate_sql.py",
    "",
]

for drug in parsed:
    name = drug.get("chineseName")
    if not name:
        continue

    chinese_chars = drug.get("chineseCharacters")
    latin       = drug.get("latinName")
    french      = drug.get("frenchName")
    nature      = drug.get("nature")
    dosage      = drug.get("dosage")
    notes       = drug.get("additionalNotes")
    category    = drug["_category"]

    nature_val  = q(nature) if nature in {"HOT", "WARM", "NEUTRAL", "COOL", "COLD"} else "NULL"
    cat_subq    = f"(SELECT id FROM drug_category WHERE name = {q(category)})"

    v4_lines.append(f"-- {name}")
    v4_lines.append(
        f"INSERT INTO drugs "
        f"(chinese_name, chinese_characters, latin_name, french_name, "
        f"nature, dosage, additional_notes, number_of_stars, category_id) VALUES ("
        f"{q(name)}, {q(chinese_chars)}, {q(latin)}, {q(french)}, "
        f"{nature_val}, {q(dosage)}, {q(notes, 1000)}, 0, {cat_subq}"
        f");"
    )

    drug_subq = f"(SELECT id FROM drugs WHERE chinese_name = {q(name)})"

    for flavor in (drug.get("flavors") or []):
        valid = {"SOUR", "BITTER", "SWEET", "PUNGENT", "SALTY", "BLAND", "AROMATIC"}
        if flavor in valid:
            v4_lines.append(
                f"INSERT INTO drug_flavors (drug_id, flavor) VALUES ({drug_subq}, '{flavor}');"
            )

    for tropism in (drug.get("tropism") or []):
        valid = {"LIVER", "GALLBLADDER", "HEART", "SMALL_INTESTINE", "SPLEEN",
                 "STOMACH", "LUNGS", "LARGE_INTESTINE", "KIDNEYS", "BLADDER",
                 "PERICARDIUM", "TRIPLE_BURNER"}
        if tropism in valid:
            v4_lines.append(
                f"INSERT INTO drug_tropism (drug_id, tropism) VALUES ({drug_subq}, '{tropism}');"
            )

    for movement in (drug.get("movements") or []):
        valid = {"ASCENDING", "DESCENDING", "OUTWARD", "INWARD"}
        if movement in valid:
            v4_lines.append(
                f"INSERT INTO drug_movement (drug_id, movements) VALUES ({drug_subq}, '{movement}');"
            )

    for effect in (drug.get("effects") or []):
        v4_lines.append(
            f"INSERT INTO drug_effects (drug_id, effect) VALUES ({drug_subq}, {q(effect, 1000)});"
        )

    for ci in (drug.get("contraindications") or []):
        v4_lines.append(
            f"INSERT INTO drug_contraindications (drug_id, contraindication) "
            f"VALUES ({drug_subq}, {q(ci, 1000)});"
        )

    v4_lines.append("")

# ── V5 — associations ────────────────────────────────────────────────────────

v5_lines = [
    "-- Seed drug associations",
    "-- Generated by generate_sql.py",
    "-- Skips associations where the partner drug is not in the DB",
    "",
]

for drug in parsed:
    name = drug.get("chineseName")
    if not name:
        continue

    for assoc in (drug.get("associations") or []):
        partner = assoc.get("associatedDrugPinyin", "").strip()
        if not partner or normalize(partner) not in known_pinyin:
            continue

        drug_subq    = f"(SELECT id FROM drugs WHERE chinese_name = {q(name)})"
        partner_subq = f"(SELECT id FROM drugs WHERE chinese_name = {q(partner)})"
        assoc_subq   = (
            f"(SELECT id FROM drug_association "
            f"WHERE drug_id = {drug_subq} AND associated_drug_id = {partner_subq})"
        )

        # Guard: only insert if both drugs exist
        v5_lines.append(
            f"INSERT INTO drug_association (drug_id, associated_drug_id) "
            f"SELECT {drug_subq}, {partner_subq} "
            f"WHERE EXISTS (SELECT 1 FROM drugs WHERE chinese_name = {q(name)}) "
            f"  AND EXISTS (SELECT 1 FROM drugs WHERE chinese_name = {q(partner)});"
        )

        for effect in (assoc.get("effects") or []):
            v5_lines.append(
                f"INSERT INTO drug_association_effects (association_id, effect) "
                f"VALUES ({assoc_subq}, {q(effect, 255)});"
            )

    v5_lines.append("")

# ── write files ───────────────────────────────────────────────────────────────

MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)

files = {
    "V3__seed_categories.sql": v3_lines,
    "V4__seed_drugs.sql": v4_lines,
    "V5__seed_associations.sql": v5_lines,
}

for filename, lines in files.items():
    path = MIGRATIONS_DIR / filename
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written: {path}  ({len(lines)} lines)")

print(f"\nSummary:")
print(f"  {len(unique_categories)} categories")
print(f"  {len(parsed)} drugs")
assoc_count = sum(len(d.get("associations") or []) for d in parsed)
print(f"  {assoc_count} associations (before filtering unknown partners)")
