"""
Generate V11__seed_new_drugs.sql from drugs_parsed.json + drugs_chunks.json.

Handles special cases:
- "Wu zei gu / Hai piao xiao" → stored as "Wu zei gu", "Hai piao xiao" added to alternative_names
- "(Bai) jiang can" → already in DB as "Bai jiang can", only add its associations
- "Hu tao ren" → already in DB (V4), only add its associations
"""

import json
import pathlib
import re

MIGRATIONS_DIR = pathlib.Path("../src/main/resources/db/migration")
HAS_CHINESE = re.compile(r"[一-鿿㐀-䶿]")

# Drugs already in DB — skip INSERT, but still emit associations
ALREADY_IN_DB = {"Hu tao ren", "Bai jiang can", "Bai bian dou"}

# Renames to apply at the start of V11 (DB name → canonical name) with optional category fix
DB_RENAMES = {
    "Bai Bian dou": ("Bai bian dou", "Ingrédients qui tonifient le Qi"),
}

# Parsed name → canonical DB name (for drugs that need renaming)
CANONICAL_NAME = {
    "Wu zei gu / Hai piao xiao": "Wu zei gu",
    "(Bai) jiang can": "Bai jiang can",
}

# Canonical name → extra alternative names to insert in alternative_names table
ALTERNATIVE_NAMES = {
    "Wu zei gu": ["Hai piao xiao"],
}

# Manual category overrides for drugs whose chunk pinyin differs from canonical name
CATEGORY_OVERRIDE = {
    "Bai dou kou": "Ingrédients aromatiques qui transforment l'Humidité",
    "Bai bian dou": "Ingrédients qui tonifient le Qi",
    "Nü zhen zi": "Ingrédients qui tonifient le Yin",
}


def clean_category(raw: str) -> str:
    s = re.sub(r"\s*\([^)]*(?:[一-鿿㐀-䶿]|[a-z]{2,}\s+[a-z])[^)]*\)\s*$", "", raw)
    s = re.sub(r"\s+[A-Z][a-z]+(?:\s+[a-z]+)+(?:\s+[一-鿿㐀-䶿]+)+\s*$", "", s)
    return s.strip()


def q(value, max_len: int = 255) -> str:
    if value is None:
        return "NULL"
    truncated = str(value)[:max_len]
    return "'" + truncated.replace("'", "''") + "'"


def normalize(name: str) -> str:
    return re.sub(r"\s+", " ", name.strip().lower())


# ── load data ────────────────────────────────────────────────────────────────

with open("drugs_parsed.json", encoding="utf-8") as f:
    parsed: list[dict] = json.load(f)

with open("drugs_chunks.json", encoding="utf-8") as f:
    chunks: list[dict] = json.load(f)

# Category lookup: normalized pinyin → clean category name
category_by_pinyin: dict[str, str] = {}
for c in chunks:
    key = normalize(c["pinyin"])
    category_by_pinyin[key] = clean_category(c["category"])

# Resolve category for each parsed drug
for drug in parsed:
    raw_name = drug.get("chineseName", "")
    canonical = CANONICAL_NAME.get(raw_name, raw_name)
    # Try canonical name, then both parts of slash names
    cat = None
    for lookup in [normalize(canonical), normalize(raw_name)] + [
        normalize(p.strip()) for p in raw_name.split("/")
    ]:
        cat = category_by_pinyin.get(lookup)
        if cat:
            break
    drug["_canonical"] = canonical
    drug["_category"] = CATEGORY_OVERRIDE.get(canonical) or cat or "Unknown"

# Collect categories that need inserting (only for new drugs)
new_drug_names = {
    CANONICAL_NAME.get(d["chineseName"], d["chineseName"])
    for d in parsed
    if CANONICAL_NAME.get(d["chineseName"], d["chineseName"]) not in ALREADY_IN_DB
}
new_categories: dict[str, None] = {}
for drug in parsed:
    if drug["_canonical"] not in ALREADY_IN_DB:
        new_categories[drug["_category"]] = None

# ── build SQL ────────────────────────────────────────────────────────────────

lines = [
    "-- V11: seed new drugs detected by updated chunk_drugs.py",
    "-- Generated by generate_v11.py",
    "-- Idempotent: ON CONFLICT DO NOTHING on drugs; WHERE NOT EXISTS on categories/associations",
    "",
    "-- ── Pre-flight fixes ────────────────────────────────────────────────────────",
    "",
]

for old_name, (new_name, new_cat) in DB_RENAMES.items():
    lines.append(f"UPDATE drugs SET chinese_name = {q(new_name)} WHERE chinese_name = {q(old_name)};")
    if new_cat:
        lines.append(
            f"UPDATE drugs SET category_id = (SELECT id FROM drug_category WHERE name = {q(new_cat)})"
            f" WHERE chinese_name = {q(new_name)};"
        )

lines += [
    "",
    "-- ── Categories ──────────────────────────────────────────────────────────────",
    "",
]

for cat in new_categories:
    lines.append(
        f"INSERT INTO drug_category (name)"
        f" SELECT {q(cat)}"
        f" WHERE NOT EXISTS (SELECT 1 FROM drug_category WHERE name = {q(cat)});"
    )

lines += ["", "-- ── Drugs ───────────────────────────────────────────────────────────────────", ""]

valid_natures    = {"HOT", "WARM", "NEUTRAL", "COOL", "COLD"}
valid_flavors    = {"SOUR", "BITTER", "SWEET", "PUNGENT", "SALTY", "BLAND", "AROMATIC"}
valid_tropism    = {"LIVER", "GALLBLADDER", "HEART", "SMALL_INTESTINE", "SPLEEN",
                    "STOMACH", "LUNGS", "LARGE_INTESTINE", "KIDNEYS", "BLADDER",
                    "PERICARDIUM", "TRIPLE_BURNER"}
valid_movements  = {"ASCENDING", "DESCENDING", "OUTWARD", "INWARD"}

for drug in parsed:
    canonical = drug["_canonical"]
    if canonical in ALREADY_IN_DB:
        continue

    nature_val = q(drug.get("nature")) if drug.get("nature") in valid_natures else "NULL"
    cat_subq = f"(SELECT id FROM drug_category WHERE name = {q(drug['_category'])})"
    drug_subq = f"(SELECT id FROM drugs WHERE chinese_name = {q(canonical)})"

    lines.append(f"-- {canonical}")
    lines.append(
        f"INSERT INTO drugs (chinese_name, chinese_characters, latin_name, french_name,"
        f" nature, dosage, additional_notes, number_of_stars, category_id) VALUES ("
        f"{q(canonical)}, {q(drug.get('chineseCharacters'))}, {q(drug.get('latinName'))},"
        f" {q(drug.get('frenchName'))}, {nature_val}, {q(drug.get('dosage'))},"
        f" {q(drug.get('additionalNotes'), 1000)}, 0, {cat_subq}"
        f") ON CONFLICT (chinese_name) DO NOTHING;"
    )

    # Alternative names
    for alt in ALTERNATIVE_NAMES.get(canonical, []):
        lines.append(
            f"INSERT INTO alternative_names (drug_id, name)"
            f" SELECT {drug_subq}, {q(alt)}"
            f" WHERE NOT EXISTS (SELECT 1 FROM alternative_names WHERE drug_id = {drug_subq} AND name = {q(alt)});"
        )

    for flavor in (drug.get("flavors") or []):
        if flavor in valid_flavors:
            lines.append(
                f"INSERT INTO drug_flavors (drug_id, flavor) VALUES ({drug_subq}, '{flavor}');"
            )

    for tropism in (drug.get("tropism") or []):
        if tropism in valid_tropism:
            lines.append(
                f"INSERT INTO drug_tropism (drug_id, tropism) VALUES ({drug_subq}, '{tropism}');"
            )

    for movement in (drug.get("movements") or []):
        if movement in valid_movements:
            lines.append(
                f"INSERT INTO drug_movement (drug_id, movements) VALUES ({drug_subq}, '{movement}');"
            )

    for effect in (drug.get("effects") or []):
        lines.append(
            f"INSERT INTO drug_effects (drug_id, effect) VALUES ({drug_subq}, {q(effect, 1000)});"
        )

    for ci in (drug.get("contraindications") or []):
        lines.append(
            f"INSERT INTO drug_contraindications (drug_id, contraindication)"
            f" VALUES ({drug_subq}, {q(ci, 1000)});"
        )

    lines.append("")

lines += ["-- ── Associations ────────────────────────────────────────────────────────────", ""]

for drug in parsed:
    canonical = drug["_canonical"]
    assocs = drug.get("associations") or []
    if not assocs:
        continue

    drug_subq = f"(SELECT id FROM drugs WHERE chinese_name = {q(canonical)})"

    for assoc in assocs:
        partner_raw = (assoc.get("associatedDrugPinyin") or "").strip()
        if not partner_raw:
            continue
        partner_subq = f"(SELECT id FROM drugs WHERE chinese_name = {q(partner_raw)})"

        # Idempotent association insert using JOIN pattern
        lines.append(
            f"INSERT INTO drug_association (drug_id, associated_drug_id)"
            f" SELECT d.id, p.id"
            f" FROM drugs d JOIN drugs p ON p.chinese_name = {q(partner_raw)}"
            f" WHERE d.chinese_name = {q(canonical)}"
            f"   AND NOT EXISTS ("
            f"SELECT 1 FROM drug_association WHERE drug_id = d.id AND associated_drug_id = p.id);"
        )

        for effect in (assoc.get("effects") or []):
            lines.append(
                f"INSERT INTO drug_association_effects (association_id, effect)"
                f" SELECT da.id, {q(effect)}"
                f" FROM drug_association da"
                f" JOIN drugs d ON d.id = da.drug_id AND d.chinese_name = {q(canonical)}"
                f" JOIN drugs p ON p.id = da.associated_drug_id AND p.chinese_name = {q(partner_raw)}"
                f" WHERE NOT EXISTS ("
                f"SELECT 1 FROM drug_association_effects WHERE association_id = da.id AND effect = {q(effect)});"
            )

    lines.append("")

# ── write file ───────────────────────────────────────────────────────────────

MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)
out_path = MIGRATIONS_DIR / "V11__seed_new_drugs.sql"
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

new_drug_count = sum(
    1 for d in parsed
    if d["_canonical"] not in ALREADY_IN_DB
)
assoc_count = sum(len(d.get("associations") or []) for d in parsed)
print(f"Written: {out_path}")
print(f"  {new_drug_count} new drugs")
print(f"  {len(new_categories)} new categories to insert")
print(f"  {assoc_count} associations (all partners guarded by JOIN pattern)")
print()
print("New drugs:")
for d in parsed:
    canonical = d["_canonical"]
    status = "(already in DB — assocs only)" if canonical in ALREADY_IN_DB else ""
    print(f"  [{d['_category'][:50]}]  {canonical} {status}")
