CREATE TABLE drug_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE drugs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chinese_name     VARCHAR(255) NOT NULL UNIQUE,
    latin_name       VARCHAR(255),
    french_name      VARCHAR(255),
    nature           VARCHAR(255) CHECK (nature IN ('HOT', 'WARM', 'NEUTRAL', 'COOL', 'COLD')),
    dosage           VARCHAR(255),
    number_of_stars  INTEGER,
    additional_notes VARCHAR(1000),
    category_id      BIGINT REFERENCES drug_category (id)
);

CREATE TABLE drug_association (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id             BIGINT REFERENCES drugs (id),
    associated_drug_id  BIGINT REFERENCES drugs (id),
    UNIQUE (drug_id, associated_drug_id)
);

CREATE TABLE alternative_names (
    drug_id BIGINT NOT NULL REFERENCES drugs (id),
    name    VARCHAR(255)
);

CREATE TABLE drug_flavors (
    drug_id BIGINT      NOT NULL REFERENCES drugs (id),
    flavor  VARCHAR(255) CHECK (flavor IN ('SOUR', 'BITTER', 'SWEET', 'PUNGENT', 'SALTY', 'BLAND', 'AROMATIC'))
);

CREATE TABLE drug_tropism (
    drug_id BIGINT      NOT NULL REFERENCES drugs (id),
    tropism VARCHAR(255) CHECK (tropism IN ('LIVER', 'GALLBLADDER', 'HEART', 'SMALL_INTESTINE', 'SPLEEN', 'STOMACH', 'LUNGS', 'LARGE_INTESTINE', 'KIDNEYS', 'BLADDER', 'PERICARDIUM', 'TRIPLE_BURNER'))
);

CREATE TABLE drug_movement (
    drug_id   BIGINT      NOT NULL REFERENCES drugs (id),
    movements VARCHAR(255) CHECK (movements IN ('ASCENDING', 'DESCENDING', 'OUTWARD', 'INWARD'))
);

CREATE TABLE drug_contraindications (
    drug_id         BIGINT NOT NULL REFERENCES drugs (id),
    contraindication VARCHAR(1000)
);

CREATE TABLE drug_effects (
    drug_id BIGINT NOT NULL REFERENCES drugs (id),
    effect  VARCHAR(1000)
);

CREATE TABLE drug_association_effects (
    association_id BIGINT NOT NULL REFERENCES drug_association (id),
    effect         VARCHAR(255)
);
