-- Fix category names: strip trailing pinyin and Chinese characters
-- Generated by generate_sql.py

UPDATE drug_category SET name = 'Ingrédients émollients lubrifiants' WHERE name = 'Ingrédients émollients lubrifiants (run xia yao 潤下藥)';
UPDATE drug_category SET name = 'Ingrédients qui activent le sang et traitent les traumatismes' WHERE name = 'Ingrédients qui activent le sang et traitent les traumatismes Huo xue liao shang yao 活血療傷藥';
UPDATE drug_category SET name = 'Ingrédients qui réchauffent et transforment les mucosités Froid' WHERE name = 'Ingrédients qui réchauffent et transforment les mucosités Froid Wen hua han tan yao 溫化寒痰藥';
UPDATE drug_category SET name = 'Ingrédients qui activent le sang et arrêtent les douleurs' WHERE name = 'Ingrédients qui activent le sang et arrêtent les douleurs Huo xue zhi tong yao 活血止痛藥';
UPDATE drug_category SET name = 'Ingrédients qui favorisent la digestion' WHERE name = 'Ingrédients qui favorisent la digestion Xiao shi yao 消食藥';
UPDATE drug_category SET name = 'Ingrédients qui transforment la stase et arrêtent les saignements' WHERE name = 'Ingrédients qui transforment la stase et arrêtent les saignements Hua yu zhi xue yao 化瘀止血藥';
UPDATE drug_category SET name = 'Ingrédients qui régularisent le Qi' WHERE name = 'Ingrédients qui régularisent le Qi Li qi yao 理氣藥';
UPDATE drug_category SET name = 'Ingrédients qui arrêtent la toux et calment la dyspnée' WHERE name = 'Ingrédients qui arrêtent la toux et calment la dyspnée Zhi ke ping chuan yao 止咳平喘藥';
UPDATE drug_category SET name = 'Ingrédients astringents qui arrêtent les saignements' WHERE name = 'Ingrédients astringents qui arrêtent les saignements Shou se zhi xue yao 收澀止血藥';
UPDATE drug_category SET name = 'Ingrédients qui tonifient le Yang' WHERE name = 'Ingrédients qui tonifient le Yang Bu yang yao 補陽藥';
UPDATE drug_category SET name = 'Ingrédients qui rafraichissent le sang et arrêtent les saignements' WHERE name = 'Ingrédients qui rafraichissent le sang et arrêtent les saignements Liang xue zhi xue yao 涼血止血藥';
UPDATE drug_category SET name = 'Ingrédients qui expulsent les parasites' WHERE name = 'Ingrédients qui expulsent les parasites Qu chong yao 驅蟲藥';
UPDATE drug_category SET name = 'Ingrédients qui réchauffent l’interne' WHERE name = 'Ingrédients qui réchauffent l’interne Wen li yao 溫里藥';
UPDATE drug_category SET name = 'Ingrédients aromatiques qui transforment l’Humidité' WHERE name = 'Ingrédients aromatiques qui transforment l’Humidité Fang xiang hua shi yao 芳香化濕藥';
UPDATE drug_category SET name = 'Ingrédients qui tonifient le Qi' WHERE name = 'Ingrédients qui tonifient le Qi Bu qi yao 補氣藥';
UPDATE drug_category SET name = 'Ingrédients qui tonifient le Yin' WHERE name = 'Ingrédients qui tonifient le Yin Bu yin yao 補陰藥';
UPDATE drug_category SET name = 'Ingrédients piquants et tièdes qui libèrent la surface du Vent-Froid' WHERE name = 'Ingrédients piquants et tièdes qui libèrent la surface du Vent-Froid (fa san fenghan xin wen yao 發散風寒辛溫藥)';
UPDATE drug_category SET name = 'Ingrédients qui activent le sang et régularisent les règles' WHERE name = 'Ingrédients qui activent le sang et régularisent les règles Huo xue tiao jing yao 活血調經藥';
UPDATE drug_category SET name = 'Ingrédients qui clarifient et transforment les mucosités Chaleur' WHERE name = 'Ingrédients qui clarifient et transforment les mucosités Chaleur Qing hua re tan yao 清化熱痰藥';
UPDATE drug_category SET name = 'Ingrédients qui tonifient le sang' WHERE name = 'Ingrédients qui tonifient le sang Bu xue yao 補血藥';
UPDATE drug_category SET name = 'Ingrédients qui réchauffent les méridiens et arrêtent les saignements' WHERE name = 'Ingrédients qui réchauffent les méridiens et arrêtent les saignements Wen jing zhi xue yao 溫經止血藥';
UPDATE drug_category SET name = 'Ingrédients purgatifs' WHERE name = 'Ingrédients purgatifs (gong xia yao 攻下藥)';
UPDATE drug_category SET name = 'Ingrédients qui ouvrent les orifices' WHERE name = 'Ingrédients qui ouvrent les orifices Kai qiao yao 開竅藥';
UPDATE drug_category SET name = 'Ingrédients qui brisent le sang et qui réduisent les masses fixes' WHERE name = 'Ingrédients qui brisent le sang et qui réduisent les masses fixes Po xue xiao zheng yao 破血消癥藥';
UPDATE drug_category SET name = 'Ingrédients lourds qui stabilisent et calment l’esprit' WHERE name = 'Ingrédients lourds qui stabilisent et calment l’esprit Zhong zhen an shen yao 重鎮安神藥';
UPDATE drug_category SET name = 'Ingrédients qui nourrissent le Cœur et calment l’esprit' WHERE name = 'Ingrédients qui nourrissent le Cœur et calment l’esprit Yang xin an shen yao 養心安神藥';
